### ISSUE TITLE
[Bug] Dashboards with CustomFields defaulting to 1.

### ISSUE THREAD

**Issue by OlivierGTelia** [TheHive-Project/TheHive#1932] opened 2021-04-06 08:46 UTC
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        |  RedHat   |
| OS version (client)        | 10          |
| TheHive version / git hash | 4.1.2            |
| Package Type               | RPM |
| Browser type & version     | Chrome and Firefox Tested                  |

### Problem Description
Hi, After the 4.1.2 Upgrade it seems that on dashboards any graph with customFields do not display properly anymore:
![image](https://user-images.githubusercontent.com/78533798/113682288-4546f780-96c3-11eb-97ed-024ec968694e.png)
Graph settings:
![image](https://user-images.githubusercontent.com/78533798/113682636-a66ecb00-96c3-11eb-9aad-52133b48dd4a.png)

All other graphs are working as expected, however all customFields graphs are defaulting to "1" for graph results, if I click on the graph it clearly shows there are more than 1 result.
This bug started with 4.1.2 for us, graphs have not been changed and where working perfectly fine before. We also tried creating new graphs in the hopes that this would solve it, however the same thing appears. 
The number in the middle shows the correct number of results based on what we have found. The bug is only presents on the chart around it.

The same bug is present on two different systems.

### Steps to Reproduce
1. Create a donut dashboard with a aggregation on a customFields. The problem should appear. I am not sure if this is only the donut which is affected or if others are affected aswell. We mainly use donuts.

**Comment by nadouani** [comment] 2021-04-06 09:07
Hello, this is a duplicate of #1921

**Closed by nadouani** 2021-04-06 09:07 UTC
Labels: TheHive4, duplicate
