### ISSUE TITLE
Merging cases functionality missing

### ISSUE THREAD

**Issue by analyst444** [TheHive-Project/TheHive#1622] opened 2020-11-05 17:17 UTC
We do not have the ability to merge cases in The Hive. The facing arrows simply does not exist. Is there a way to fix this? 
![hive1](https://user-images.githubusercontent.com/71147104/98273901-a6697400-1f47-11eb-9082-0d63aa164b43.PNG)

**Comment by nadouani** [comment] 2020-11-08 12:31
Closing as duplicate of #1264

**Closed by nadouani** 2020-11-08 12:31 UTC
Labels: duplicate
