### ISSUE TITLE
Add query capability to visualization elements

### ISSUE THREAD

**Issue by dotwayland** [TheHive-Project/TheHive#395] opened 2017-12-08 20:00 UTC
### Request Type
Feature Request

Add the ability to click on a visualization element and display the cases which correspond to that measurement. For example, being able to click on the portion of the chart that represents any case that is "Open" would result in a list of Open cases being displayed. 

![image001](https://user-images.githubusercontent.com/9294978/33782876-fe4c1bd2-dc1f-11e7-9b5c-6916842cd435.png)

**Comment by nadouani** [comment] 2018-01-31 15:06
I didn't see this issue, and created a duplicate of it #453 that has been fixed for 3.0.4

**Closed by nadouani** 2018-01-31 15:06 UTC
Labels: duplicate
