### ISSUE TITLE
[Bug] Unable to close cases via the Web Interface

### ISSUE THREAD

**Issue by trocade** [TheHive-Project/TheHive#1711] opened 2020-12-16 07:46 UTC
# Unable to close cases via webui

### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04 LTS
| OS version (client)       | 10
| TheHive version / git hash   | 4.0.2
| Package Type              | DEB
| Browser type & version    | Chrome 83.0.4103.116

### Problem Description
When closing a case the WEB-ui informs that the case is closed succesfully but it remains in open state.
It is possible to close the same case via the API.

### Steps to Reproduce
1. Create a new case or use a old case
1. Close the case and set resolution

### Complementary information
```
2020-12-16 07:37:47,903 [DEBUG] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Begin of transaction
2020-12-16 07:37:47,904 [DEBUG] from org.thp.thehive.services.CaseSrv in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[]), HasStep([_label.eq(Case), ~label.eq(Case), ~id.eq(81952880)]), TraversalFilterStep([VertexStep(IN,[ShareCase],vertex), TraversalFilterStep([VertexStep(OUT,[ShareProfile],vertex), HasStep([permissions.eq(manageCase)])]), VertexStep(IN,[OrganisationShare],vertex), HasStep([~id.eq(40964208)])])] (update)
2020-12-16 07:37:47,904 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[]), HasStep([_label.eq(Case), ~label.eq(Case), ~id.eq(81952880)]), TraversalFilterStep([VertexStep(IN,[ShareCase],vertex), TraversalFilterStep([VertexStep(OUT,[ShareProfile],vertex), HasStep([permissions.eq(manageCase)])]), VertexStep(IN,[OrganisationShare],vertex), HasStep([~id.eq(40964208)])])] (headOption)
2020-12-16 07:37:47,912 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81952880]), HasStep([_label.eq(Case), ~label.eq(Case)])] (headOption)
2020-12-16 07:37:47,913 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[]), HasStep([_label.eq(ResolutionStatus), ~label.eq(ResolutionStatus), value.eq(FalsePositive)])] (headOption)
2020-12-16 07:37:47,914 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81952880]), HasStep([_label.eq(Case), ~label.eq(Case)]), VertexStep(OUT,[CaseResolutionStatus],edge)] (drop)
2020-12-16 07:37:47,915 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81952880])] (headOption)
2020-12-16 07:37:47,915 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[4336])] (headOption)
2020-12-16 07:37:47,915 [DEBUG] from org.thp.thehive.services.AuditSrv in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Audit is disable to the current transaction, Audit(0884909111f4c364:-71d86f45:1766a68235b:-8000:199,update,false,Some(~81952880),Some(Case),Some({"resolutionStatus":"FalsePositive"})) ignored.
2020-12-16 07:37:47,915 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81952880]), HasStep([_label.eq(Case), ~label.eq(Case)])] (headOption)
2020-12-16 07:37:47,916 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[]), HasStep([_label.eq(CustomField), ~label.eq(CustomField), name.eq(False Positive)])] (headOption)
2020-12-16 07:37:47,918 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81952880]), HasStep([_label.eq(Case), ~label.eq(Case)]), VertexStep(OUT,[CaseCustomField],edge), ProjectStep([32fb1e1c-8af4-4d58-b2a4-a39884fac34d, 065ddcec-0e66-4e53-ac0f-74a8a546ec0d],[identity, [EdgeVertexStep(IN)]])] (toIterator)
2020-12-16 07:37:47,919 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81952880]), HasStep([_label.eq(Case), ~label.eq(Case)]), VertexStep(OUT,[CaseCustomField],edge), TraversalFilterStep([EdgeVertexStep(IN), HasStep([name.eq(False Positive)])])] (exists)
2020-12-16 07:37:47,919 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81952880]), HasStep([_label.eq(Case), ~label.eq(Case)]), VertexStep(OUT,[CaseCustomField],edge), TraversalFilterStep([EdgeVertexStep(IN), HasStep([name.eq(False Positive)])])@[5c492bf9-c1c4-4abc-b1aa-d0e8df8ef7f5], EdgeVertexStep(IN), PropertiesStep([type],value)@[010e5191-4b15-477d-9cbd-e1c71bbbb1ff], SelectStep(last,[5c492bf9-c1c4-4abc-b1aa-d0e8df8ef7f5, 010e5191-4b15-477d-9cbd-e1c71bbbb1ff])] (toSeq)
2020-12-16 07:37:47,920 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[]), HasStep([_label.eq(Case), ~label.eq(Case), ~id.eq(81952880)]), TraversalFilterStep([VertexStep(IN,[ShareCase],vertex), TraversalFilterStep([VertexStep(OUT,[ShareProfile],vertex), HasStep([permissions.eq(manageCase)])]), VertexStep(IN,[OrganisationShare],vertex), HasStep([~id.eq(40964208)])])] (headOption)
2020-12-16 07:37:47,922 [DEBUG] from org.thp.thehive.services.AuditSrv in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Hold Audit(0884909111f4c364:-71d86f45:1766a68235b:-8000:199,update,false,Some(~81952880),Some(Case),Some({"summary":"Some(fdsfsf)","resolutionStatus":"FalsePositive","customFields":{"False Positive":{"order":0,"integer":1}}})), store previous audit if any
2020-12-16 07:37:47,922 [DEBUG] from org.thp.thehive.services.AuditSrv in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Setup callbacks for the current transaction
2020-12-16 07:37:47,922 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[]), HasStep([_label.eq(Case), ~label.eq(Case), ~id.eq(81952880)]), TraversalFilterStep([VertexStep(IN,[ShareCase],vertex), TraversalFilterStep([VertexStep(OUT,[ShareProfile],vertex), HasStep([permissions.eq(manageCase)])]), VertexStep(IN,[OrganisationShare],vertex), HasStep([~id.eq(40964208)])]), ProjectStep([e4b9f8c3-9a42-43c4-a697-503b1312e7bd, a5bc7c4a-90be-4b0c-8cb2-ec7feb414246, aca7af82-fe2d-4088-a70f-591f120f6fa7, 2aad962c-440c-4ce4-b52f-eefbd5c3a33b, 84bf9d54-47c9-4e23-9643-d593f0dbfc2f, ef3dcf22-d7b8-4b98-9152-647047591946, 4f1f7da2-b1a0-4aea-bbfc-60493e230492],[identity, [VertexStep(OUT,[CaseTag],vertex), FoldStep], [VertexStep(OUT,[CaseImpactStatus],vertex), PropertiesStep([value],value), FoldStep], [VertexStep(OUT,[CaseResolutionStatus],vertex), PropertiesStep([value],value), FoldStep], [VertexStep(OUT,[CaseUser],vertex), PropertiesStep([login],value), FoldStep], [VertexStep(OUT,[CaseCustomField],edge), ProjectStep([6b62f9b0-11c3-4aad-8bf8-3ef84f01f5c8, c150a3d1-3b78-444b-9f34-70a203056716],[identity, [EdgeVertexStep(IN)]]), FoldStep], [VertexStep(IN,[ShareCase],vertex), TraversalFilterStep([VertexStep(IN,[OrganisationShare],vertex), HasStep([~id.eq(40964208)])]), VertexStep(OUT,[ShareProfile],vertex)]])] (headOption)
2020-12-16 07:37:47,936 [DEBUG] from org.thp.thehive.services.AuditSrv in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Store last audit
2020-12-16 07:37:47,936 [DEBUG] from org.thp.thehive.services.AuditSrv in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Store audit entity: Audit(0884909111f4c364:-71d86f45:1766a68235b:-8000:199,update,true,Some(~81952880),Some(Case),Some({"summary":"Some(fdsfsf)","resolutionStatus":"FalsePositive","customFields":{"False Positive":{"order":0,"integer":1}}}))
2020-12-16 07:37:47,936 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[]), HasStep([_label.eq(User), ~label.eq(User), login.eq(someuser@domain)])] (headOption)
2020-12-16 07:37:48,608 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[163844184])] (headOption)
2020-12-16 07:37:48,608 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81924208])] (headOption)
2020-12-16 07:37:48,609 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[163844184])] (headOption)
2020-12-16 07:37:48,609 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81952880])] (headOption)
2020-12-16 07:37:48,609 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[163844184])] (headOption)
2020-12-16 07:37:48,610 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Execution of [GraphStep(vertex,[81952880])] (headOption)
2020-12-16 07:37:48,611 [DEBUG] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Committing transaction
2020-12-16 07:37:48,616 [DEBUG] from org.thp.thehive.services.AuditSrv in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] Sending audit to stream bus and to notification actor
2020-12-16 07:37:48,616 [DEBUG] from org.thp.scalligraph.services.EventSrv in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] publish stream AuditStreamMessage(List(~163844184))
2020-12-16 07:37:48,617 [DEBUG] from org.thp.thehive.services.notification.NotificationActor in application-akka.actor.default-dispatcher-17 [|] Receive AuditStreamMessage(~163844184)
2020-12-16 07:37:48,617 [DEBUG] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-21 [|3d1b6be4] Begin of readonly transaction
2020-12-16 07:37:48,617 [DEBUG] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-17 [|27a83588] Begin of readonly transaction
2020-12-16 07:37:48,617 [DEBUG] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-23 [|054e3b2b] Begin of readonly transaction
2020-12-16 07:37:48,618 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-21 [|3d1b6be4] Execution of [GraphStep(vertex,[163844184]), HasStep([_label.eq(Audit), ~label.eq(Audit)]), TraversalFilterStep([VertexStep(OUT,[AuditContext],vertex), CoalesceStep([[HasStep([~label.eq(Organisation)])], [VertexStep(IN,vertex), HasStep([~label.eq(Share)]), VertexStep(IN,[OrganisationShare],vertex)], [VertexStep(BOTH,vertex), HasStep([~label.eq(Organisation)])]]), HasStep([~id.eq(40964208)])])] (toSeq)
2020-12-16 07:37:48,620 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-17 [|27a83588] Execution of [GraphStep(vertex,[163844184]), HasStep([_label.eq(Audit), ~label.eq(Audit)]), ProjectStep([9c9cf5b6-cbc9-4e75-8759-884770384a3b, a477a39e-aaee-4e1e-84bb-4c3f42074a7f, 8c788f60-b0c5-4cea-b074-9456d940fd07, e7e9904a-0321-4a66-a689-233b414ed6ea],[identity, [VertexStep(OUT,[AuditContext],vertex), FoldStep], [VertexStep(OUT,[Audited],vertex), FoldStep], [VertexStep(OUT,[AuditContext],vertex), CoalesceStep([[HasStep([~label.eq(Organisation)])], [VertexStep(IN,vertex), HasStep([~label.eq(Share)]), VertexStep(IN,[OrganisationShare],vertex)], [VertexStep(BOTH,vertex), HasStep([~label.eq(Organisation)])]]), FoldStep]])] (toIterator)
2020-12-16 07:37:48,620 [DEBUG] from org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher-23 [|054e3b2b] Execution of [GraphStep(vertex,[163844184]), HasStep([_label.eq(Audit), ~label.eq(Audit), mainAction.eq(true)]), ProjectStep([497f45cf-6771-488c-a729-a0d7f3801e47, 5f321777-4ff5-4f40-b44b-7f673269b107, 60f9adc6-b6d1-4c26-8141-6889bdd47824],[[IdStep], [VertexStep(OUT,[AuditContext],vertex), CoalesceStep([[HasStep([~label.eq(Organisation)])], [VertexStep(IN,vertex), HasStep([~label.eq(Share)]), VertexStep(IN,[OrganisationShare],vertex)], [VertexStep(BOTH,vertex), HasStep([~label.eq(Organisation)])]]), IdStep, FoldStep], [VertexStep(OUT,[AuditContext],vertex), CoalesceStep([[VertexStep(IN,vertex), HasStep([~label.eq(Share)])], [HasStep([~label.eq(Share)])]]), VertexStep(OUT,[ShareCase],vertex), IdStep, FoldStep]])] (toIterator)
2020-12-16 07:37:48,621 [DEBUG] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-22 [000000c7|5a0ca603] End of transaction
```

The following script will close the case without any problem:
```
#!/usr/bin/python3

import requests
import sys
import json
import time
import uuid
from thehive4py.api import TheHiveApi
from thehive4py.models import Alert, AlertArtifact, CustomFieldHelper

api = TheHiveApi('http://127.0.0.1:9000', 'SECRET')

hiveCase = api.case('case_id')
hiveCase.status='Resolved'
hiveCase.resolutionStatus='TruePositive'
hiveCase.impactStatus='NoImpact'
hiveCase.tags=['mytag']
hiveCase.summary='my summary'

hiveResponse = api.update_case(hiveCase,['status', 'resolutionStatus', 'impactStatus', 'tags', 'summary'])

if hiveResponse.status_code == 200:
    print(json.dumps(hiveResponse.json(), indent=4, sort_keys=True))
else:
    print('ko: {}/{}'.format(hiveResponse.status_code, hiveResponse.text))

```

**Comment by trocade** [comment] 2020-12-17 15:38
A update to this is that we found that some cases can be closed via web-ui. Investigating why they can be closed. 
Other than that we are now running a script to close the case for us once a day.

**Comment by nadouani** [comment] 2020-12-21 06:02
Hello @trocade interested on any feedback that helps reproducing this. Thanks

**Comment by trocade** [comment] 2020-12-21 07:38
Hello @nadouani 

This is what I have done so far and noted down, one thing that would be very good is if it possible to increase verbosity to the logfile during the case closure.

I managed to find a very interesting example:
In this case I found that I can not close the case in the dev environment but the assigned users successfully closed it in production.
In our case dev and production are exact copies.

This user can only close certain cases not all.

I have replicated the steps:

### The steps taken in both are:
1. Assign to user
1. Go to tasks (2 tasks are in the case)
2. Start and then close each task with a comment.
3. Close the with status and a short summary.

When I close I get a message saying my case was successfully closed but the case is only updated not 

## Case status after I close in dev environment
```
Updated by <username> 2 minutes
[ALARM] FROM (P) YARA
resolutionStatus: FalsePositive
summary: Some(A test closure)
customFields: {}
  #11391 - [ALARM] FROM (P) YARA 
```

## Case status in production environment 

```
 Closed by <username>
  [ALARM] FROM (P) YARA
endDate: Fri, Dec 18th, 2020 11:34 +01:00
summary: Some(False positive)
customFields: {}
resolutionStatus: FalsePositive
status: Resolved
impactStatus: NotApplicable
  #11391 - [ALARM] FROM (P) YARA 
```

**Comment by MatheusChein** [comment] 2021-01-08 19:17
I'm having a similar problem. 

We developed an API that listens on a certain port. Everytime a case is closed on TheHive, it sends a JSON to that port, containing all the information about that case. We parse that information and can use it as we like.

However, even though the JSON is sent, indicating that the case was actually closed, that same case remains open on the Web Interface. I wasn't sure that if my API was the one causing this problem, but after findind this issue, I'm thinking it's not.

@trocade were you able to find a solution to this problem? It'd be really helpful if you did.

Thanks.

**Comment by trocade** [comment] 2021-01-10 22:47
@MatheusChein 

The only solution that we have right now is that one of the org-admins run a script that closes all cases set to resolved via the api interface.

**Comment by trocade** [comment] 2021-01-21 07:59
I have updated to 4.0.4 and the issue remain. I would need some advice what to provide to get further on in troubleshooting.

There are some users that manages to close cases and other users are not able.
They follow the exact same procedure when closing.

**Comment by MatheusChein** [comment] 2021-01-21 13:47
@trocade 

So, I found a problem on my API, there were some error handling that could've been done better. And because of that, TheHive was having some perfomance issues. 

After I addressed that problem, the users were able to close the cases via the Web UI with no problems. I don't know if that helps you, but it was the solution I found. So far, it's working.

**Comment by trocade** [comment] 2021-01-22 10:39
@MatheusChein 

That is interesting, we have one application that is doing very heavy calls to the API. Do you mind share what you did see in the logs?

**Comment by MatheusChein** [comment] 2021-01-23 12:12
@trocade 

Since my API is listening on a certain port, every event happening on TheHive was been posted to that same port, didn't matter if it was an alert, a case, a case artifact and so on. So, I had to filter the requests to accept only cases, which is what we needed.

However, cases were being posted there not only when they were closed, but also when they were created, or had any alerts merged to them. This was causing a problem, because the point of the API was to go through the alerts inside every closed case. 

Since it was all going to the same endpoint, the API was trying to go through the case to find the alerts inside it, even when they were just being created, instead of when they were closed, increasing the number os calls happening, which caused those performance issues.

When I fixed this, filtering it to accept only closed cases, the problem was gone. 

I don't know how you're calling the API in your case, but that was the situation for me and how I fixed it, hope this explanation could be useful for you.

**Comment by trocade** [comment] 2021-01-29 07:24
@MatheusChein ,

I don't think we are hit by this, the API calls are mainly to create alerts (and my little close-case implementation).

**Comment by nadouani** [comment] 2021-02-22 14:22
Hello, @trocade this is a TheHive4py issue. Could you please create a github entry for it on TheHive4py repo? Thanks

**Closed** 2021-02-22 14:22 UTC
Labels: TheHive4, invalid

**Comment by trocade** [comment] 2021-02-23 09:53
Hello @nadouani I think the discussion about what caused the problem is confusing. @MatheusChein confirmed his issue was caused by the thehive4api but it is not that in our case.

So for us this is still valid even with 4.0.5 that when closing a case using the close button on the webui the cases remain in open state.
