### ISSUE TITLE
[Bug] Dashboard not counting custom field occurrences correctly

### ISSUE THREAD

**Issue by Passimist** [TheHive-Project/TheHive#1955] opened 2021-04-12 13:02 UTC
### Work Environment
TheHive 4.1.1-1
Play 2.8.7
Scaligraph o.1.0-SNAPSHOT

### Problem Description
The dashboard bar graphs do not correctly count how many cases contain specific values in a customfield.
### Steps to Reproduce
1. Add a customfield (issuetest)
2. Add 3 new cases (1, 2, 2B)
![image](https://user-images.githubusercontent.com/53262314/114398050-a24d1c80-9b9f-11eb-97b9-a5f5dfca9ee3.png)

3. Add the issuetest customfield to the cases with the value 1, 2 and 2 (so 2 is the value of this customfield in 2 cases)
4. Create new dashboard
![image](https://user-images.githubusercontent.com/53262314/114398250-dd4f5000-9b9f-11eb-8662-196d0979c3c6.png)

5. Be confused about the graphic telling you each value occurred just once.
![image](https://user-images.githubusercontent.com/53262314/114398379-053eb380-9ba0-11eb-8556-b92d3be3bf5f.png)

**Comment by nadouani** [comment] 2021-04-12 15:15
Closed as duplicate of #1921

**Closed by nadouani** 2021-04-12 15:15 UTC
Labels: TheHive4, duplicate
