### ISSUE TITLE
[Bug] Marking an alert as read do not update it's "updatedAt" nor "updatedBy" field

### ISSUE THREAD

**Issue by Dilaw9** [TheHive-Project/TheHive#2292] opened 2021-12-15 16:05 UTC
### Request Type
Bug

### Work Environment

TheHive 4.1.15

### Problem Description
Marking as read an alert do not update its "updatedAt" nor "updatedBy" field when searching the alert with the /api/alert/_search API call.
### Steps to Reproduce
1 - create an alert.
2 - mark it as read.
3 - search this same alert through the search panel of TheHive UI

### Complementary information
This bug also impacts TheHive4py.api find_alerts() method as it also relies on the /api/alert/_search API call.

**Comment by To-om** [comment] 2021-12-16 13:29
dupliates #2262

**Comment by Dilaw9** [comment] 2021-12-16 13:50
Hi @To-om,

Thanks for your reply.

Though, I'm sorry I don't understand why this issue was closed as duplicate. It is not the exact same issue.
The issue I'm describing here is still existing in the latest release (4.1.15). 

The "updatedAt" and"updatedBy" fields always have a "null" value even when the alert has been maked as read. This issue is visible when searching an alert with the **/api/alert/_search API call**. (With the search panel from TheHive Web UI or with the TheHive4py.api find_alerts() function for instance).

**Comment by To-om** [comment] 2021-12-16 13:59
weird, I've just checked and I can't reproduce this behaviour.
How do you mark as read ? Using the web interface of TheHive ?

**Comment by Dilaw9** [comment] 2021-12-16 14:10
Yes I mark as read via the web interface of TheHive.

Here are screenshots of the results I get:
Here I'm searching a specific alert (filtering with sourceRef) on the Alert panel of the Web interface:
![image](https://user-images.githubusercontent.com/38134974/146386600-6f7c18fa-8f97-4b00-85b8-a3bd0e7e63c9.png)

And there I'm searching the same alert using the Search panel of the Web interface (selecting "Alert" search scope and filtering on sourceRef):
![image](https://user-images.githubusercontent.com/38134974/146387001-ccf022bb-f116-4461-9787-6d132a5e24c1.png)
I have the same result when using find_alerts() function in TheHive4py.api.

As you can see, same alert object, but the updatedAt and updatedBy have a "null" value.

**Comment by To-om** [comment] 2021-12-16 15:03
Thank you @Dilaw9 for this issue. It is now fixed.

**Closed** 2021-12-16 15:03 UTC
Labels: bug, TheHive4
