### ISSUE TITLE
[Bug] Not importing alert into case

### ISSUE THREAD

**Issue by rafalszymanek** [TheHive-Project/TheHive#1665] opened 2020-11-18 10:56 UTC
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS Linux release 8.2.2004 (Core)
| OS version (client)       | MacOS 
| TheHive version / git hash   | 4.0.1-1
| Package Type              | Binary
| Browser type & version    | Safari v.14.0.1 

### Problem Description
Alerts are not imported to case.
It creates new case with all parameters from selected alerts, but alerts are not attached in a case.

In previous version it worked properly.
When we created case from alert/alerts it attached these alerts into that case and marked these alerts as “Imported”. No meter it was importing via “New case from selection” button or from other possibilities using API.

### Steps to Reproduce
1. Go to Alerts page
2. Select alert or alerts and create case from selection
3. Go to case
4. Case doesn't have attached alert/alerts into that case
<img width="570" alt="Screenshot 2020-11-18 at 11 52 54" src="https://user-images.githubusercontent.com/30106887/99521491-c6138a00-2994-11eb-8ae7-1baace07a10b.png">

5. Imported alerts are not marked as "Imported"
<img width="546" alt="Screenshot 2020-11-18 at 11 54 21" src="https://user-images.githubusercontent.com/30106887/99521561-d9265a00-2994-11eb-9a50-a2bda7e91b73.png">

### Complementary information
Only way to really import alert to case is by using API:
POST http://127.0.0.1:9000/api/alert/:AlertID/createCase

It creates case from alert and marked is as “Imported”.
<img width="558" alt="Screenshot 2020-11-18 at 11 45 20" src="https://user-images.githubusercontent.com/30106887/99520570-8ac48b80-2993-11eb-94b4-1d941a9e7671.png">

All other ways to create case from alert or merge alert into case doesn't attach these alerts into case.

**Comment by nadouani** [comment] 2020-11-18 13:20
This one is duplicate of #1648 which has been fixed in 4.0.2. Thanks

**Closed** 2020-11-18 13:20 UTC
Labels: TheHive4, duplicate
