### ISSUE TITLE
Feature Request: Ability to bulk upload files as observables.

### ISSUE THREAD

**Issue by mrod42** [TheHive-Project/TheHive#435] opened 2018-01-17 16:57 UTC
Feature Request

### Problem Description
When working in a case with multiple binaries which need to be added as observables, there is no mechanism to bulk upload those files.

### Request
The ability to bulk upload like binaries as observables to a case.

**Comment by saadkadhi** [comment] 2018-01-17 20:38
Hi @mrod42 

This is a duplicate of #327.

**Closed by saadkadhi** 2018-01-17 20:38 UTC

**Comment by mrod42** [comment] 2018-01-17 20:40
thanks! i guess i did not read carefuly enough when trying to avoid a dupe
request!
