### ISSUE TITLE
[Bug] Slow getting case observables via API get_case_observables

### ISSUE THREAD

**Issue by jpferrero** [TheHive-Project/TheHive#2218] opened 2021-10-14 13:12 UTC
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | CentOS 7  |
| Virtualized  Env.          |  True                          |
| Dedicated RAM              | 3x16 GB                                 |
| vCPU                       |  8 each node                       |
| TheHive version   | 4.11           |
| Package Type               | RPM |
| Database                   | Cassandra                |
| Index type                 |  Elasticsearch                |
| Attachments storage        | HDFS                  |

### Problem Description

Trying to get observables from a case_id via TheHive4py, it takes more than 3 minutes to run the query.

This is the TheHive4py call:

api = TheHiveApi(THEHIVE_URL, THEHIVE_API_KEY, cert=False)
api.get_case_observables("~492589064", query={}, sort=['-startDate', '+ioc'], range='all')

Time:

real	3m22.734s
user	0m0.141s
sys	0m0.023s

There are a total of 367848 of observables and 24872 cases in our database.

Thanks.

**Comment by torsolaso** [comment] 2021-10-21 10:12
I think this is related to https://github.com/TheHive-Project/TheHive/issues/2149

There are several querys not migrated from thv3 to thv4

**Comment by To-om** [comment] 2021-11-25 10:22
This issue has been fixed by #2225

**Closed by To-om** 2021-11-25 10:22 UTC
Labels: bug, TheHive4

**Comment by zohkoo** [comment] 2021-12-01 15:17
> This issue has been fixed by #2225

We updated our instance to TheHive 4.1.13 and the issue is still there. I've made a test this afternoon and it tooks 20 minutes to retrieve the observables of a specific case via `get_case_observables`. I'm not sure it has really been fixed by #2225 

I can confirm that the workaround proposed by @jpferrero is also working for us.

**Comment by ch0wm3in** [comment] 2021-12-22 14:38
We have the same problem on 4.1.14
