### ISSUE TITLE
SSL & LDAP Authentication - Docker Image Not Working

### ISSUE THREAD

**Issue by disclosurez** [TheHive-Project/TheHive#1181] opened 2019-12-10 16:28 UTC
### Request Type
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |RedHat
| OS version (client)       | Rhel 7 - Docker Image
| TheHive version / git hash   | 3.x
| Package Type              | Docker
| Browser type & version    | If applicable

### Problem Description
Describe the problem/bug as clearly as possible.

### Steps to Reproduce
1. Enable LDAP 
2. Enable SSL

Getting this error

```
thehive_1        | [error] o.e.s.a.ADAuthSrv - AD authentication failure
thehive_1        | javax.naming.CommunicationException: simple bind failed: xxx.xxxx.xxxx:636
thehive_1        |      at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:219)
thehive_1        |      at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2791)
thehive_1        |      at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
thehive_1        |      at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
thehive_1        |      at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
thehive_1        |      at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
thehive_1        |      at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
thehive_1        |      at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
thehive_1        |      at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
thehive_1        |      at javax.naming.InitialContext.init(InitialContext.java:244)
thehive_1        | Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
thehive_1        |      at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
thehive_1        |      at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
thehive_1        |      at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
thehive_1        |      at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
thehive_1        |      at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
thehive_1        |      at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
thehive_1        |      at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
thehive_1        |      at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
thehive_1        |      at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
thehive_1        |      at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
thehive_1        | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
thehive_1        |      at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
thehive_1        |      at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)

```

I have tried:
1. exporting the root CA certificate and copying it to the server

2. running this:  
`keytool -importcert -trustcacerts -file ca.cer  -keystore /home/xxxxx/thehive-docker/config/keystore.jks`

3. setting this in docker image:
```
    environment:
      - JAVA_OPTS=-Djavax.net.ssl.trustStore=/home/xxxxx/thehive-docker/config/keystore.jks
```

**Comment by disclosurez** [comment] 2020-01-23 10:26
Any updates please? Am I doing this wrong?

**Comment by jaredjennings** [comment] 2020-01-30 00:20
It appears you are following [this piece of documentation](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#31-ldapad). The issue is that paths on your host machine are not equivalent to paths inside the Docker container. I think you need to [bind-mount](https://docs.docker.com/compose/compose-file/#volumes) your keystore into your container then refer to the in-container path.

If you are using the docker-compose.yml as found in this repo, maybe write in it like so:

```yaml
version: "2"
services:
  # ...
  thehive:
    # ...
    volumes:
      - type: bind
        source: /home/xxxxx/thehive-docker/config/keystore.jks
        target: /etc/thehive/keystore.jks
    environment:
      - JAVA_OPTS=-Djavax.net.ssl.trustStore=/etc/thehive/keystore.jks
```

**Comment by To-om** [comment] 2020-04-06 06:54
@jaredjennings is right. I close this issue

**Closed by To-om** 2020-04-06 06:54 UTC
Labels: question
