### ISSUE TITLE
[Bug] The button "Merge in this case" in alert similarity doesn't work

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#1516] opened 2020-09-08 15:26 UTC
### Request Type
Bug

### Work Environment
TheHive 4.0.0

### Problem Description
In alert similarity modal, the button "Merge in this case" doesn't do anything (no error)

**Comment by nadouani** [comment] 2020-09-28 14:17
Closing as duplicate of #1470

**Closed by nadouani** 2020-09-28 14:17 UTC
Labels: duplicate
